/*
 * Copyright 2026 the RecordRelay authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.recordrelay.engine.clone;

import static org.assertj.core.api.Assertions.assertThat;

import io.recordrelay.core.clone.domain.BusinessEntity;
import io.recordrelay.core.clone.domain.ConflictResolution;
import io.recordrelay.core.clone.domain.ContextClonePlan;
import io.recordrelay.core.clone.domain.FieldOverride;
import io.recordrelay.core.clone.domain.FieldOverrideConfig;
import io.recordrelay.core.clone.domain.MaskingConfig;
import io.recordrelay.core.clone.domain.SatelliteConfig;
import io.recordrelay.core.clone.domain.SatelliteTable;
import io.recordrelay.core.clone.port.out.CloneProgressListener;
import io.recordrelay.core.domain.ConnectionProfile;
import io.recordrelay.core.domain.Credentials;
import io.recordrelay.core.domain.DatabaseType;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.List;
import java.util.Map;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

/**
 * End-to-end integration test for the satellite (companion-database) sync.
 *
 * <p>Simulates the real-world topology: a core database ({@code beyanname} + child rows) is cloned
 * into a test core database, while a separate user-module database keeps a {@code read_model}
 * projection that references {@code beyanname} only by a logical {@code beyanname_id}. After the
 * clone, the satellite sync must copy the projection into the test user database with {@code
 * beyanname_id} remapped to the newly allocated id and the field overrides applied.
 *
 * <p>Four logical databases live in one container: {@code core_src}, {@code core_tgt}, {@code
 * user_src}, {@code user_tgt}.
 */
@Tag("integration")
@Testcontainers
class SatelliteCloneIT {

  @Container
  static final PostgreSQLContainer<?> PG =
      new PostgreSQLContainer<>("postgres:16-alpine")
          .withDatabaseName("postgres")
          .withUsername("tester")
          .withPassword("secret");

  @BeforeAll
  static void setUp() throws Exception {
    // Create the four databases (CREATE DATABASE cannot run inside a transaction).
    try (var admin = adminConnection();
        var stmt = admin.createStatement()) {
      stmt.execute("CREATE DATABASE core_src");
      stmt.execute("CREATE DATABASE core_tgt");
      stmt.execute("CREATE DATABASE user_src");
      stmt.execute("CREATE DATABASE user_tgt");
    }

    // Core source: a beyanname with two child rows (real FK for deterministic traversal).
    exec(
        "core_src",
        "CREATE TABLE beyanname ("
            + "  id BIGINT PRIMARY KEY,"
            + "  mukellef_vkn VARCHAR(32) NOT NULL,"
            + "  durum VARCHAR(16) NOT NULL)",
        "CREATE TABLE beyanname_kalem ("
            + "  id BIGINT PRIMARY KEY,"
            + "  beyanname_id BIGINT NOT NULL REFERENCES beyanname(id),"
            + "  tutar NUMERIC(10,2) NOT NULL)",
        "INSERT INTO beyanname(id, mukellef_vkn, durum) VALUES (12, '1111111111', 'ONAY')",
        "INSERT INTO beyanname_kalem(id, beyanname_id, tutar) VALUES (1, 12, 100.00), (2, 12, 200.00)");

    // Core target: same schema, empty.
    exec(
        "core_tgt",
        "CREATE TABLE beyanname ("
            + "  id BIGINT PRIMARY KEY,"
            + "  mukellef_vkn VARCHAR(32) NOT NULL,"
            + "  durum VARCHAR(16) NOT NULL)",
        "CREATE TABLE beyanname_kalem ("
            + "  id BIGINT PRIMARY KEY,"
            + "  beyanname_id BIGINT NOT NULL REFERENCES beyanname(id),"
            + "  tutar NUMERIC(10,2) NOT NULL)");

    // User source: a read_model projection referencing beyanname only by beyanname_id (no FK).
    exec(
        "user_src",
        "CREATE TABLE read_model ("
            + "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "  beyanname_id BIGINT NOT NULL,"
            + "  mukellef_vkn VARCHAR(32) NOT NULL,"
            + "  kullanici_kod VARCHAR(64) NOT NULL,"
            + "  beyanname_turu VARCHAR(32) NOT NULL)",
        "INSERT INTO read_model(id, beyanname_id, mukellef_vkn, kullanici_kod, beyanname_turu)"
            + " VALUES (500, 12, '1111111111', 'OLDUSER', 'KDV')");

    // User target: same schema, empty.
    exec(
        "user_tgt",
        "CREATE TABLE read_model ("
            + "  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
            + "  beyanname_id BIGINT NOT NULL,"
            + "  mukellef_vkn VARCHAR(32) NOT NULL,"
            + "  kullanici_kod VARCHAR(64) NOT NULL,"
            + "  beyanname_turu VARCHAR(32) NOT NULL)");
  }

  /** Resets the target databases before each test so the cases stay independent of each other. */
  @BeforeEach
  void resetTargets() throws Exception {
    exec(
        "core_tgt",
        "ALTER TABLE beyanname ALTER COLUMN id DROP DEFAULT",
        "DROP SEQUENCE IF EXISTS beyanname_seq",
        "TRUNCATE beyanname_kalem, beyanname");
    exec("user_tgt", "TRUNCATE read_model");
  }

  @Test
  void syncsReadModelIntoUserTargetWithRemappedIdAndOverrides() throws Exception {
    var entity = BusinessEntity.of("beyanname", "beyanname", "id", "");
    var overrides =
        new FieldOverrideConfig(
            List.of(
                FieldOverride.global("mukellef_vkn", "9999999999"),
                FieldOverride.global("kullanici_kod", "NEWUSER")));
    var satellites =
        new SatelliteConfig(
            List.of(
                SatelliteTable.of(
                    profile("user_src"), profile("user_tgt"), "read_model", "beyanname_id")));

    var plan =
        ContextClonePlan.liveCloneWithOverrides(
            entity,
            "12",
            profile("core_src"),
            profile("core_tgt"),
            3,
            MaskingConfig.none(),
            overrides,
            ConflictResolution.REGENERATE_IDENTITIES,
            satellites);

    DefaultContextCloneEngine.createDefault().cloneContext(plan, new CloneProgressListener() {});

    // The root got a freshly allocated id in the core target (>= source max of 12).
    long newBeyannameId = queryLong("core_tgt", "SELECT id FROM beyanname");
    assertThat(newBeyannameId).isGreaterThanOrEqualTo(13L);
    // Override was applied to the core row too.
    assertThat(queryString("core_tgt", "SELECT mukellef_vkn FROM beyanname"))
        .isEqualTo("9999999999");

    // The satellite read_model landed in the user target …
    assertThat(queryLong("user_tgt", "SELECT COUNT(*) FROM read_model")).isEqualTo(1L);
    // … with beyanname_id remapped to the new core id …
    assertThat(queryLong("user_tgt", "SELECT beyanname_id FROM read_model"))
        .isEqualTo(newBeyannameId);
    // … and the same field overrides applied.
    assertThat(queryString("user_tgt", "SELECT mukellef_vkn FROM read_model"))
        .isEqualTo("9999999999");
    assertThat(queryString("user_tgt", "SELECT kullanici_kod FROM read_model"))
        .isEqualTo("NEWUSER");
    // The untouched projection column carried over verbatim.
    assertThat(queryString("user_tgt", "SELECT beyanname_turu FROM read_model")).isEqualTo("KDV");
  }

  @Test
  void startAtAllocatesRootIdFromRequestedValue() throws Exception {
    var entity = BusinessEntity.of("beyanname", "beyanname", "id", "");

    var plan =
        ContextClonePlan.liveCloneWithOverrides(
            entity,
            "12",
            profile("core_src"),
            profile("core_tgt"),
            3,
            MaskingConfig.none(),
            FieldOverrideConfig.none(),
            ConflictResolution.START_AT,
            SatelliteConfig.none(),
            500_000L);

    DefaultContextCloneEngine.createDefault().cloneContext(plan, new CloneProgressListener() {});

    assertThat(queryLong("core_tgt", "SELECT id FROM beyanname")).isEqualTo(500_000L);
    // Children's FK was remapped to the requested root id.
    assertThat(queryLong("core_tgt", "SELECT DISTINCT beyanname_id FROM beyanname_kalem"))
        .isEqualTo(500_000L);
  }

  @Test
  void sequenceAllocatesRootIdFromNativeSequence() throws Exception {
    // Give beyanname an identity sequence in the target so SEQUENCE has something to pull from.
    exec(
        "core_tgt",
        "CREATE SEQUENCE IF NOT EXISTS beyanname_seq START 7000",
        "ALTER TABLE beyanname ALTER COLUMN id SET DEFAULT nextval('beyanname_seq')",
        "ALTER SEQUENCE beyanname_seq OWNED BY beyanname.id");

    var entity = BusinessEntity.of("beyanname", "beyanname", "id", "");
    var plan =
        ContextClonePlan.liveCloneWithOverrides(
            entity,
            "12",
            profile("core_src"),
            profile("core_tgt"),
            3,
            MaskingConfig.none(),
            FieldOverrideConfig.none(),
            ConflictResolution.SEQUENCE,
            SatelliteConfig.none(),
            null);

    DefaultContextCloneEngine.createDefault().cloneContext(plan, new CloneProgressListener() {});

    // The id came from beyanname_seq (>= its start), not from max(id)+1.
    assertThat(queryLong("core_tgt", "SELECT id FROM beyanname")).isGreaterThanOrEqualTo(7000L);
  }

  // ── helpers ────────────────────────────────────────────────────────────────

  private static ConnectionProfile profile(String database) {
    return new ConnectionProfile(
        database,
        "test",
        "env-1",
        DatabaseType.POSTGRESQL,
        PG.getHost(),
        PG.getMappedPort(PostgreSQLContainer.POSTGRESQL_PORT),
        database,
        new Credentials(PG.getUsername(), PG.getPassword()),
        Map.of());
  }

  private static Connection adminConnection() throws Exception {
    return DriverManager.getConnection(PG.getJdbcUrl(), PG.getUsername(), PG.getPassword());
  }

  private static String jdbcUrl(String database) {
    return "jdbc:postgresql://"
        + PG.getHost()
        + ":"
        + PG.getMappedPort(PostgreSQLContainer.POSTGRESQL_PORT)
        + "/"
        + database;
  }

  private static void exec(String database, String... sql) throws Exception {
    try (var conn =
            DriverManager.getConnection(jdbcUrl(database), PG.getUsername(), PG.getPassword());
        var stmt = conn.createStatement()) {
      for (var s : sql) {
        stmt.execute(s);
      }
    }
  }

  private static long queryLong(String database, String sql) throws Exception {
    try (var conn =
            DriverManager.getConnection(jdbcUrl(database), PG.getUsername(), PG.getPassword());
        var stmt = conn.createStatement();
        var rs = stmt.executeQuery(sql)) {
      rs.next();
      return rs.getLong(1);
    }
  }

  private static String queryString(String database, String sql) throws Exception {
    try (var conn =
            DriverManager.getConnection(jdbcUrl(database), PG.getUsername(), PG.getPassword());
        var stmt = conn.createStatement();
        var rs = stmt.executeQuery(sql)) {
      rs.next();
      return rs.getString(1);
    }
  }
}
